import { enumField, EnumField, U3BytesField } from "./RolandAddressMap";
import { pack7 } from "./RolandSysExProtocol";

// The Tone Bank Select MSB field (first byte of Patch PCM Tone) is always 0x58,
// except for the last 14 tones (the Drums category), which have an MSB of 0x56.
// Writing to the BS LSB + PC fields (second and third bytes) works even if we
// ignore the MSB, but reading from them requires us to parse the MSB correctly.
// This array encodes the correct MSB for each tone.
// TODO: Encode and render categories (source here: https://www.vguitarforums.com/smf/index.php?topic=3060.0)
const tonesAndOffsets = [
  [
    pack7(0x580000),
    [
      "St.Piano 1",
      "St.Piano 2",
      "St.Piano 3",
      "St.Piano 4",
      "St.Piano 5",
      "Brite Piano",
      "Stage Piano",
      "Honky Tonk",
      "LoFi Piano",
      "Piano 1",
      "Piano 1 w",
      "European Pf",
      "Piano 2",
      "Piano 2 w",
      "Honky-tonk",
      "Honky-tonk w",
      "Pop Piano 1",
      "Pop Piano 2",
      "Pop Piano 3",
      "Piano 3",
      "Piano 3 w",
      "Stage EP 1",
      "Stage EP 2",
      "Stage EP Trm",
      "Tremolo EP 1",
      "E. Piano 1",
      "E. Piano 2",
      "E. Piano 3",
      "E. Piano 4",
      "E. Piano 5",
      "E. Piano 6",
      "Dyno EP",
      "Dyno EP Trm",
      "Tremolo EP 2",
      "Back2the60s",
      "Tine EP",
      "SA EP 1",
      "SA EP 2",
      "Psy EP",
      "Wurly EP",
      "Wurly EP Trm",
      "Curly Wurly",
      "Super Wurly",
      "E. Piano 7",
      "St. Soft EP",
      "Wurly",
      "EP Legend 1",
      "EP Belle",
      "80's EP",
      "FM EP 1",
      "FM EP 2",
      "Sinus EP",
      "Spirit Tines",
      "EP Legend 2",
      "E. Piano 8",
      "Detuned EP",
      "St. FM EP",
      "EP Legend 3",
      "EP Phase",
      "Rock Organ 1",
      "Rock Organ 2",
      "Rock Organ 3",
      "Rock Organ 4",
      "Rock Organ 5",
      "RotaryOrgan1",
      "RotaryOrgan2",
      "Perc.Organ 1",
      "Perc.Organ 2",
      "Perc.Organ 3",
      "E.Organ 1",
      "E.Organ 2",
      "E.Organ 3",
      "E.Organ 4",
      "E.Organ 5",
      "E.Organ 6",
      "E.Organ 7",
      "70's E.Org 1",
      "70's E.Org 2",
      "Ana Organ 1",
      "Ana Organ 2",
      "Ana Organ 3",
      "Ana Organ 4",
      "Ana Organ 5",
      "Organ 1",
      "Trem. Organ",
      "60's Organ",
      "70's E.Organ",
      "Organ 2",
      "Chorus Organ",
      "Perc.Organ 4",
      "Organ 3",
      "Grand Pipes",
      "Church Org 1",
      "Church Org 2",
      "Church Org 3",
      "Puff Organ",
      "Reed Organ",
      "Harpsichord1",
      "Harpsichord2",
      "Coupled Hps",
      "Harpsi w",
      "Harpsi o",
      "Clav 1",
      "Pulse Clav 1",
      "Sweepin Clav 1",
      "Analog Clav",
      "Biting Clav",
      "Pulse Clv St",
      "Clav 2",
      "Pulse Clav 2",
      "Celesta",
      "AccordionIt2",
      "Musette",
      "Vodkakordion",
      "Accordion Fr",
      "Accordion It",
      "Bandoneon",
      "Harmonica 1",
      "Harmonica 2",
      "FM Sparkles",
      "Fm Syn Bell",
      "FM Heaven",
      "Dreaming Bel",
      "Analog Bell",
      "Music Box 1",
      "Music Bells",
      "Kalimbells",
      "Bell 1",
      "Bell 2",
      "Icy Keys",
      "Carillon 1",
      "Tower Bell",
      "Tubularbell2",
      "Bell Ring",
      "Music Box 2",
      "TubularBells",
      "Church Bell",
      "Carillon 2",
      "Crystal",
      "Tinkle Bell",
      "Toy Box",
      "Vibraphone 1",
      "VibraphoneTr",
      "Tremolo Vib",
      "Marimba 1",
      "Marimba 2",
      "Steel Drums 1",
      "Xylophone 1",
      "Xylophone 2",
      "Ethno Keys",
      "Soft StlDrm",
      "Jazz Vib",
      "BsMarimba 1",
      "BsMarimba 2",
      "Sine Mallet",
      "Glockenspeil",
      "Vibraphone 2",
      "Vibraphone w",
      // NOTE: Listed as "Marimba 2" which is a duplicate
      "Marimba 2*",
      "Marimba w",
      "Xylophone 3",
      "SteelDrums 2",
      "Nylon Gtr 1",
      "Nylon Gtr 2",
      "Nylon Gtr 3",
      "Nylon Gtr 4",
      "Wet Nyln Gtr",
      "Ukulele 1",
      "Folk Gtr 1",
      "Folk Gtr 2",
      "Folk Gtr 3",
      "Latin Gtr",
      "Nylon Gtr 5",
      "Ukulele 2",
      "Nylon Gtr 5o",
      "Nylon Gtr 6",
      "Steel-str.Gt",
      "12-str. Gtr",
      "Steel + Body",
      "Gt FretNoise",
      "Clean Gtr 1",
      "Clean Gtr 2",
      "Clean Gtr 3",
      "JazzGuitar 1",
      "Pick E.Gtr",
      "FunkGuitar 1",
      "Wet E.Gtr",
      "PedalSteel 1",
      "JazzGuitar 2",
      "PedalSteel 2",
      "Clean Guitar",
      "Chorus Gtr",
      "Mid Tone Gtr",
      "Muted Guitar",
      "Funk Pop",
      "FunkGuitar 2",
      "Jazz Man",
      "Gt Cut Noise",
      "OverdriveGt1",
      "Dist Gtr 1",
      "Dist Gtr 2",
      "Dist Gtr 3",
      "OverdriveGtr2",
      "Guitar Pinch",
      "DistortionGt",
      "Gt Feedback1",
      "Dist Rtm Gtr",
      "Gt Harmonics",
      "Gt Feedback2",
      "AcousticBs 1",
      "AcousticBs 2",
      "AcousticBs 3",
      "String Slap",
      "FingeredBs 1",
      "FingeredBs 2",
      "FingeredBs 3",
      "Pick Bass",
      "FretlessBs 1",
      "FretlessBs 2",
      "Finger Slap2",
      "Return2Base!",
      "FingeredBs 4",
      "Finger Slap",
      "Picked Bass",
      "FretlessBs 3",
      "Slap Bass 1",
      "Slap Bass 2",
      "MG Bass 1",
      "MG Bass 2",
      "MG Bass 3",
      "Modular Bs 1",
      "Modular Bs 2",
      "PWM Bass 1",
      "PWM Bass 2",
      "Big Mini",
      "Fat Analog",
      "Spike Bass",
      "SH Bass",
      "Intrusive BS",
      "Synth Bass 1",
      "Synth Bass 2",
      "Synth Bass 3",
      "Synth Bass 4",
      "Synth Bass 5",
      "Synth Bass 6",
      "Synth Bass 7",
      "Synth Bass 8",
      "Synth Bass 9",
      "Synth Bass10",
      "Synth Bass11",
      "Synth Bass12",
      "Reso Bass 1",
      "Reso Bass 2",
      "Reso Bass 3",
      "Reso Bass 4",
      "Reso Bass 5",
      "Reso Bass 6",
      "Reso Bass 7",
      "Reso Bass 8",
      "Acid Bass 1",
      // NOTE: Listed as "Reso Bass 2" which is a duplicate
      "Reso Bass 2*",
      // NOTE: Listed as "Reso Bass 3" which is a duplicate
      "Reso Bass 3*",
      "Alpha Bass 1",
      "TB Bass 1",
      "TB Bass 2",
      "Alpha Bass 2",
      "Alpha ResoBs",
      "Nu Saw Bass",
      "Nu RnB SawBs",
      "Storm Bass",
      "Detuned Bass",
      "Gashed Bass",
      "Hi-Energy Bs",
      "Pedal Bass 1",
      "Monster Bass",
      "JunoSqr Bs 1",
      "JunoSqr Bs 2",
      "101 Bass",
      "106 Bass 1",
      "106 Bass 2",
      "Compu Bass 1",
      "Compu Bass 2",
      "Triangle Bs",
      "Muffled Bass",
      "Garage Bass",
      "TransistorBs",
      "Fazee Bass",
      "TB Bass 3",
      "TB Bass 4",
      "Acid Bass 4",
      "Acid Bass 5",
      "Acid Bass 6",
      "Brite Bass",
      "Pedal Bass 2",
      "Saw Bass",
      "Reso Bass 9",
      "Reso Bass 10",
      "Sub Bass",
      "Ramp Bass",
      "Fat Bass 1",
      "Fat Bass 2",
      "Fat Bass 3",
      "Flat Bass",
      "Electro Rubb",
      "80s Bass",
      "Synth Bass13",
      "SynthBass101",
      "Acid Bass 7",
      "Clav Bass",
      "Hammer Bass",
      "Synth Bass14",
      "SynSlap Bass",
      "Rubber Bass",
      "Attack Pulse",
      "Santur 1",
      "Santur 2",
      "Aerial Harp",
      "LostParadise",
      "Sitar 1",
      "Indian Frtls",
      "Sitar Pad",
      "Santur 3",
      "Mandolin",
      "Harp",
      "Yang Qin",
      "Sitar 2",
      "Sitar 3",
      "Banjo",
      "Shamisen",
      "Koto",
      "Taisho Koto",
      "Kalimba",
      "Violin 1",
      "Bright Vln",
      "Bright VC",
      "Violin 2",
      "Slow Violin",
      "Viola",
      "Cello",
      "Contrabass",
      "Fiddle",
      "Mood Strings",
      "Strings 1",
      "Strings 2",
      "Strings 3",
      "Strings 4",
      "Stage Str 1",
      "Stage Str 2",
      "Pop Str",
      "Marc. Str",
      "StringsStacc",
      "Pizz 1",
      "Pizz 2",
      "TapeStrings1",
      "TapeStrings2",
      "Hybrid Str",
      "Strings 5",
      "Hall Strings",
      "Tremolo Str",
      "PizzicatoStr",
      "Strings 6",
      "Oct Strings",
      "Slow Strings",
      "Orc. Unison 1",
      "Orc. Unison 2",
      "Full Orc",
      "Orchestra",
      "Trumpet 1",
      "Fr. Horn",
      "Trumpet 2",
      "Dark Trumpet",
      "Trombone 1",
      "Trombone 2",
      "Bright Tb",
      "Tuba",
      "MuteTrumpet1",
      "MuteTrumpet2",
      "French Horn",
      "Brass 1",
      "Brass 2",
      "Brass 3",
      "Brass 4",
      "F. Horn Sect",
      "Brass 5",
      "Brass 6",
      "Bassoon 1",
      "Oboe",
      "English Horn",
      "Bassoon 2",
      "Clarinet",
      "Bagpipe",
      "Shanai",
      "Flute 1",
      "Pan Flute 1",
      "Pan Pipes 1",
      "Shakuhachi 1",
      "Pan Pipes 2",
      "Piccolo",
      "Flute 2",
      "Pan Flute 2",
      "Bottle Blow",
      "Shakuhachi 2",
      "Breath Noise",
      "F1.Key Click",
      "Soprano Sax1",
      "BreathyTenor",
      "Tenor Sax 1",
      "Soprano Sax2",
      "Alto Sax",
      "Tenor Sax 2",
      "Baritone Sax",
      "Ocarina 1",
      "Recorder",
      "Whistle",
      "Ocarina 2",
      "Dreamvox 1",
      "Dreamvox 2",
      "Choir Pad",
      "Angels Choir",
      "Aerial Choir",
      "Doo Pad",
      "Humming 1",
      "Humming 2",
      "Gospel Hum",
      "Vox Pad 1",
      "Vox Pad 2",
      "80s Vox",
      "SynVox 1",
      "SynVox 2",
      "Mini Vox",
      "Chipmunk",
      "Sample Opera",
      "Sad Ceremony",
      "5th Voice",
      "Sop Vox",
      "Choir Aahs",
      "Chorus Aahs",
      "Voice Oohs",
      "Humming 3",
      "SynVox 3",
      "Analog Voice",
      "Space Voice",
      "Itopia",
      "Jazz Scat 1",
      "Jazz Scat 2",
      "Saw Lead 1",
      "Saw Lead 2",
      "Saw Lead 3",
      "Saw Lead 4",
      "Saw Lead 5",
      "Saw Lead 6",
      "Saw Lead 7",
      "Saw Lead 8",
      "Saw Lead 9",
      "GR300 Lead 1",
      "GR300 Lead 2",
      "Classic GR",
      "Bright GR",
      "Fat GR Lead",
      "MODified Ld",
      "Syn Lead 1",
      "Syn Lead 2",
      "Syn Lead 3",
      "Syn Lead 4",
      "Syn Lead 5",
      "Syn Lead 6",
      "Syn Lead 7",
      "Pro Fat Ld 1",
      "JupiterLead1",
      "JupiterLead2",
      "Porta Lead",
      "Classic Lead",
      "On Air",
      "Pro Fat Ld 2",
      "Wormy Lead",
      "Waspy Lead",
      "Brite ResoLd",
      "Brass Lead",
      "Legato Tkno",
      "Follow Me",
      "Octa Juice",
      "Juicy Jupe",
      "Octa Saw",
      "Vintager 1",
      "Vintager 2",
      "Sync Lead",
      "Octa Sync",
      "Leading Sync",
      "A Leader",
      "Hot Coffee",
      "Hot Sync",
      "Syncro Lead",
      "Space Solo",
      "Squareheads",
      "Mod Lead",
      "Alpha Spit",
      "Air Lead",
      "Pulstar Lead",
      "Therasaw",
      "Warmy Lead",
      "ResoSawLead",
      "Soft Reso Ld",
      "Reso Lead 1",
      "Reso Lead 2",
      "Reso Lead 3",
      "Reso Lead 4",
      "Reso Lead 5",
      "Juicy Lead",
      "DC Triangle",
      "Soft Lead 1",
      "Soft Lead 2",
      "Soft Lead 3",
      "Soft Lead 4",
      "Soft Lead 5",
      "Soft Lead 6",
      "Soft Lead 7",
      "Soft Lead 8",
      "Soft Lead 9",
      "Soft Lead 10",
      "Tri Lead",
      "Pulse Lead 1",
      "Pulse Lead 2",
      "Simple Tri",
      "Simple Sine",
      "Whistle Ld 1",
      "Whistle Ld 2",
      "Square Pipe",
      "CosmicDrops1",
      "Spooky Lead",
      "Pure Lead",
      "303 NRG",
      "Round SQR",
      "Brite SQR",
      "Square SAW",
      "Simple SQR",
      "Sqr Lead",
      "Atk Lead",
      "Octa Square",
      "CS Lead",
      "Mini Growl",
      "Hoover Again",
      "Tranceformer",
      "Juno SQR",
      "Pulse Lead 3",
      "Pulse Lead 4",
      "Ramp Lead 1",
      "Ramp Lead 2",
      "Saw Lead 10",
      "Sine Lead 1",
      "Sine Lead 2",
      "Dance Saws1",
      "Resoform",
      "Dance Saws2",
      "Square Wave",
      "MG Square",
      "2600 Sine",
      "Saw Wave",
      "OB2 Saw",
      "Doctor Solo",
      "Natural Lead",
      "Syn. Calliope",
      "Chiffer Lead",
      "Charang",
      "Wire Lead",
      "Solo Vox",
      "5th Saw Wave",
      "Bass & Lead",
      "Delayed Lead",
      "80s Brass 1",
      "80s Brass 2",
      "80s Brass 3",
      "80s Brass 4",
      "80s Brass 5",
      "80s Brass 6",
      "80s Brass 7",
      "80s Brass 8",
      "Soft SynBrs1",
      "Warm SynBrs",
      "Brite SynBrs",
      "Express Brs",
      "EuroExpress1",
      "JP Brass 1",
      "Juno Brass",
      "Ox Brass",
      "Reso Brass",
      "Wide SynBrs",
      "Soft SynBrs2",
      "JP Brass 2",
      "106 Brass",
      "Octa Brass",
      "Poly Brass 1",
      "Dual Saw Brs",
      "Jump Poly",
      "Reso Key 1",
      "EuroExpress2",
      "Ox Synth",
      "VintageBrs 1",
      "VintageBrs 2",
      "VintageBrs 3",
      "VintageBrs 4",
      "Poly Brass 2",
      "Synth Brass1",
      "JP Brass",
      "Oct SynBrass",
      "Jump Brass",
      "Synth Brass2",
      "SynBrass sfz",
      "Velo Brass",
      "Heaven Pad 1",
      "Heaven Pad 2",
      "Dreamheaven",
      "Oct Heaven",
      "Soft Pad 1",
      "Soft Pad 2",
      "Soft Pad 3",
      "Soft Pad 4",
      "Soft Pad 5",
      "Soft Pad 6",
      "Soft Pad 7",
      "Soft Pad 8",
      "Soft Pad 9",
      "Soft Pad 10",
      "VintageStr 1",
      "VintageStr 2",
      "VintageStr 3",
      "VintageStr 4",
      "VintageStr 5",
      "VintageStr 6",
      "VintageStr 7",
      "JX Strings",
      "JP Strings 1",
      "JP Strings 2",
      "106 Strings",
      "PWM Str 1",
      "PWM Str 2",
      "Fading Str",
      "ParadisePad",
      "80s Strings",
      "Stringship",
      "Airy Pad",
      "Neo RS-202",
      "Sawtooth Str",
      "Pulse Pad",
      "Hollow Pad 1",
      "WarmHeaven 1",
      "WarmHeaven 2 ",
      "Heaven Pad 3",
      "Heaven Pad 4 ",
      "FineWinePad1",
      "FineWinePad2",
      "5th Pad 1",
      "5th Pad 2",
      "Nu Epic Pad",
      "Angelis Pad",
      "TrnsSweepPad",
      "Giant Sweep",
      "Voyager",
      "Digital Pad",
      "NuSoundtrack",
      "Xadecimal",
      "Strobe Pad",
      "BUBBLE 2",
      "BUBBLE 3",
      "Soft PWM Pad",
      "Org Pad",
      "Hollow Pad 2",
      "SavannaPad 1",
      "SavannaPad 2",
      "SavannaPad 3",
      "PWM Str 3",
      "PWM Pad 2",
      "Str Machine",
      "Reso Pad",
      "BPF Pad",
      "Sweep Pad 2",
      "Sweep Pad 3 ",
      "Sweep Pad 4",
      "Scoop Pad 1",
      "Scoop Pad 2",
      "Brite Wine",
      "Wine Pad",
      "Syn. Strings1",
      "Syn. Strings3",
      "Syn. Strings2",
      "Warm Pad",
      "Sine Pad",
      "Bowed Glass",
      "Metal Pad",
      "Halo Pad",
      "Sweep Pad",
      "Soundtrack",
      "Star Theme",
      "D50 Fantasy",
      "D50 Bell",
      "Dreambell",
      "Dreaming Box",
      "Air Key 1",
      "Sweet Keys",
      "Soft Bell",
      "Air Key 2",
      "Stacc Heaven",
      "DigitalDream",
      "Analog Dream",
      "Harp Pad",
      "Org Bell",
      "Fantasia",
      "Ice Rain",
      "Atmosphere",
      "Brightness",
      "Dream Trance",
      "Dream Saws",
      "Dream Pulse",
      "Trance Synth",
      "Trancy",
      "Trance Keys",
      "Trance Saws",
      "Auto Trance1",
      "Super Saws 1",
      "Analog Saws",
      "Uni-G",
      "Digitaless",
      "Bustranza",
      "Super Saws 2",
      "Poly Synth 1",
      "Poly Synth 2",
      "Poly Synth 3",
      "Poly Synth 4",
      "Poly Synth 5",
      "Poly Synth 6",
      "Juno Saw Key",
      "Saw Key 1",
      "Saw Key 2",
      "Waspy Synth",
      "Vintage Key",
      "Ju-D Fifths",
      "Reso Key 2",
      "Fat Synth",
      "DOC Stack",
      "2 Saws",
      "Hi Saw Band",
      "Brite Synth",
      "PWM Pad 1",
      "RAVtune",
      "Heaven Key",
      "Pipe Key",
      "Shroomy",
      "AnalogDays 1",
      "Sync Key",
      "Detune Ramp",
      "Reso Saw",
      "EuroExpress3",
      "Sweep Saw",
      "Poly Synth 7",
      "Syn Mallet",
      "Enigmatic",
      "Planetz",
      "Shimmer Pad",
      "Sci-Fi",
      "ResoSweep Dn",
      "Jet Noise",
      "Brandish",
      "909 Fx",
      "Zap",
      "Polysweep Nz",
      "Passing By",
      "Lazer Points",
      "CosmicDrops2",
      "Crystal Fx",
      "Crystal Ice",
      "Mad Noise",
      "Robot Sci-Fi",
      "Computer 1",
      "Computer 2",
      "S&H Noise",
      "S&H Ramp",
      "S&H PWM",
      "S&H Saw 1",
      "S&H Saw 2",
      "Electrostar",
      "Alpha Said",
      "FX Ramp",
      "Bubble 1",
      "Goblin",
      "Echo Drops",
      "Echo Bell",
      "Analog Seq",
      "Seq Pop",
      "Periscope",
      "Major 7",
      "Juno-D Maj7",
      "Sweet House",
      "Detune Saws",
      "Melodic Drum",
      "Detune Seq",
      "SequencedSaw",
      "Echo Pan",
      "PanninFormnt",
      "Fairy's Song",
      "Atmospherics",
      "StrobeBell 1",
      "StrobeBell 2",
      "Flying Pad 1",
      "Flying Pad 2",
      "Flying Pad 3",
      "Flying Pad 4",
      "Flying Pad 5",
      "Sine Magic",
      "Pulsatron",
      "Motion Bass",
      "Trance Splt",
      "Rhythmic 5th",
      "Rhythmic 1",
      "Rhythmic 2",
      "Mega Sync 1",
      "StrobeBell 3",
      "Strobe 1",
      "Strobe 2",
      "Strobe 3",
      "Strobe 4",
      "LFO Saw",
      "Keep Going",
      "Keep Running",
      "Electrons",
      "BriskVortex",
      "LFO Vox",
      "Pulsasaw",
      "Arposphere",
      "Mega Sync 2",
      "Compusonic 1",
      "Compusonic 2",
      "Compusonic 3",
      "Compusonic 4",
      "Compusonic 5",
      "AnalogDays 2",
      "Groove 007",
      "Juno Pop",
      "Auto Trance2",
      "In Da Groove",
      "80s Beat",
      "Cheezy Movie",
      "Mod Chord",
      "Housechord",
      "OrchestraHit",
      "Bass Hit",
      "6th Hit",
      "Euro Hit",
      "Scratch 1",
      "Seashore",
      "Rain",
      "Thunder",
      "Wind",
      "Stream",
      "Bubble",
      "Bird 1",
      "Dog",
      "Horse Gallop",
      "Bird 2",
      "Telephone 1",
      "Telephone 2",
      "DoorCreaking",
      "Door",
      "Scratch 2",
      "Wind Chimes",
      "Helicopter",
      "Car Engine",
      "Car Stop",
      "Car Pass",
      "Car Crash",
      "Siren",
      "Train",
      "Jetplane",
      "Starship",
      "Burst Noise",
      "Applause",
      "Laughing",
      "Screaming",
      "Punch",
      "Heart Beat",
      "Footsteps",
      "Gun Shot",
      "Machine Gun",
      "Laser Gun",
      "Explosion",
      "Ride Cymbal",
      "Timpani",
      "Agogo",
      "Woodblock",
      "Castanets",
      "Taiko",
      "Concert BD",
      "Melo. Tom 1",
      "Melo. Tom 2",
      "Synth Drum",
      "808 Tom",
      "Elec Perc",
      "Reverse Cymb",
    ],
  ],
  [
    pack7(0x560000),
    [
      "Standard 1",
      "Standard 2",
      "Standard 3",
      "Rock Kit",
      "Jazz Kit",
      "Brush Kit",
      "Machine Kit",
      "R&B T-Analog",
      "R&B Mini Kit",
      "HipHop Kit",
      "R&B Kit",
      "Dance Kit 1",
      "Dance Kit 2",
      "Dance Kit 3",
    ],
  ],
] as const;

const pcmToneFieldStorageMapping: {
  [encoded: number]: number;
} = {};

// Stores the full list of tone labels.
const allPcmToneLabels: string[] = [];

for (const [encodedOffset, labels] of tonesAndOffsets) {
  for (const [i, label] of labels.entries()) {
    const globalToneIndex = allPcmToneLabels.push(label) - 1;
    // TODO: What happens if we do read Drum tones with MSB === 0x58?
    // i.e. encoded === (encodedOffset + globalToneIndex)
    // ideally we would normalise them silently, but currently EnumField
    // asserts that there are no duplicate values so we can't do it that way.
    pcmToneFieldStorageMapping[encodedOffset + i] = globalToneIndex;
  }
}

export const pcmToneSelectField = enumField(
  allPcmToneLabels,

  // An enum field with numeric labels (!) that serves as a lookup table between
  // logical tone numbers and the encoded values that the synth expects.
  // We go through this indirection so that `pcmToneSelectField` can be reinterpreted with
  // different storage (specifically, when used as an assign target).
  new EnumField<{ [encoded: number]: number }>(
    pcmToneFieldStorageMapping,
    new U3BytesField()
  )
);
