// In the GR-55, the patch display number is a composite of the UI bank number and the patch number within that bank.
// There are 3 patches per UI bank, so the patch display number is 01-1, 01-2, 01-3, 02-1, 02-2, 02-3, etc.
// Each "style" (LEAD, RHYTHM, OTHER or USER) has a sequential range of UI banks.
// So a string like "LEAD 01-1" or "RHYTHM 02-3" uniquely identifies a patch location.

import { pack7 } from "./RolandSysExProtocol";

// Patch contents are fixed in the GR-55's ROM for the LEAD, RHYTHM, and OTHER styles,
// so in particular we need to hardcode the patch names for these styles.
// The USER patches have addresses in the GR-55's memory so we read their names over MIDI.

const GR55_PATCHES_PER_UI_BANK = 3;
const GR55_UI_BANK_NUMBER_WIDTH = 2;

type CompositePatchNumber = [number, number]; // [UI bank, UI patch]

function buildContiguousPatches({
  styleLabel,
  fromPatchNumber,
  toPatchNumber,
  bankMSB,
  fromPC,
  fromUserPatch,
  names,
}: {
  styleLabel: string;
  fromPatchNumber: CompositePatchNumber;
  toPatchNumber: CompositePatchNumber;
  bankMSB: number;
  fromPC: number;
  fromUserPatch?: number;
  names?: readonly string[];
}) {
  const patchMap = [];
  let pc = fromPC;
  let userPatchNumber = fromUserPatch;
  let index = 0;
  for (let i = fromPatchNumber[0]; i <= toPatchNumber[0]; i++) {
    const startj = i === fromPatchNumber[0] ? fromPatchNumber[1] : 1;
    const endj =
      i === toPatchNumber[0] ? toPatchNumber[1] : GR55_PATCHES_PER_UI_BANK;
    for (let j = startj; j <= endj; j++) {
      patchMap.push({
        styleLabel,
        patchNumberLabel: `${i
          .toString()
          .padStart(GR55_UI_BANK_NUMBER_WIDTH, "0")}-${j}`,
        bankMSB,
        pc,
        userPatch:
          userPatchNumber != null
            ? {
                patchNumber: userPatchNumber,
                baseAddress:
                  pack7(0x20000000) + userPatchNumber * pack7(0x010000),
              }
            : undefined,
        builtInName: names ? names[index]! : undefined,
      });
      pc++;
      if (typeof userPatchNumber === "number") {
        userPatchNumber++;
      }
      index++;
    }
  }
  return patchMap;
}

function buildPatchMap(guitarBassSelect: "GUITAR" | "BASS") {
  /**
   * NOTE: The system patch names and patch numbers are correct as of GR-55 firmware version 1.50.
   * TODO: See if we can read the firmware version from the GR-55 and use that to switch between the 1.50 and pre-1.50 patch maps.
   *
   * Sourced from the following Roland documents:
   *   - GR-55_PA.pdf
   *   - GR-55_l_ver150attend_e01.pdf (revised bank/PC numbers)
   *   - GR-55_l_Add_PatchList_je01_W.pdf (patch names)
   */
  const patchList = [];
  switch (guitarBassSelect) {
    case "GUITAR":
      patchList.push(
        ...buildContiguousPatches({
          styleLabel: "LEAD",
          fromPatchNumber: [1, 1],
          toPatchNumber: [40, 3],
          bankMSB: 16,
          fromPC: 0,
          names: [
            "Metal Synth Lead",
            "Rock Lead Organ",
            "GR-300 Ctl:+1Oct",
            "Nice Tenor",
            "Flute Solo",
            "Jazz Guitar Vibe",
            "Legato Solo",
            "SlowAttack Solo",
            "Synth Brass Lead",
            "Drive Blues Harp",
            "Tp Section",
            "MELLOW CELLO",
            "Strange Whistle",
            "EMOTIONAL LEAD",
            "WAVE SYNTH SOLO",
            "Dual Sync Lead",
            "Funky Syn Lead",
            "SqrPipe For You",
            "Concert Grand",
            "Mute Trumpet/EXP",
            "Epf + 335 Unison",
            "P90 & Organ Bell",
            "Feedback Guitar",
            "CTL=DLY/EXP=WAH",
            "More Blacklord",
            "Pdl Bend Guitar",
            "POLY DISTOTION",
            "NaturalResoLead",
            "Organ Syn Lead",
            "Crims-O-Tron",
            "Dist Sync Lead",
            "5th Layer",
            "Screamin Lead",
            "Portamento Lead",
            "Dist Sine Solo",
            "Dist Square Lead",
            "Buzz Lead",
            "METAL SAW LEAD",
            "BrassyLead",
            "LONG ECHO LEAD",
            "RockyOrgan",
            "MILD SAW LEAD",
            "Simple Square",
            "+1oct Mild Lead",
            "Unison Lead",
            "Lead Beast",
            "Dream Bell",
            "Female Chorus",
            "70s Unison",
            "Comfortable Solo",
            "Wah Feedback",
            "Gtr+Organ Unison",
            "Vibraphone",
            "Dark Trumpet",
            "High Note Tp",
            "Fat Brass Sec",
            "Solo Fr.Horn",
            "SGT Fr Horn",
            "Solo Trombone",
            "Super Low Brass",
            "Clarinet>EXP Vib",
            "Oboe",
            "Soprano Sax",
            "Alto Sax",
            "Moody Sax",
            "Guitar+SaxUnison",
            "Flute+Gtr Unison",
            "Pan Flute",
            "Piccolo",
            "Flutey GT",
            "Heaven Ocarina",
            "LofiFlute&Glockn",
            "Recorder",
            "Chromatic Harmo",
            "FILTER HARP",
            "Gt + HARMONICA",
            "Heavy Harmonica",
            "LEAD VIOLIN",
            "DIST VIOLIN",
            "DRIVE+VLN+CELLO",
            "DOUBLE CELLO",
            "GLASS CELLO",
            "OVERDRIVE+CELLO",
            "SMOOTH LEAD+VLN",
            "Brass + Drive",
            "Organ,Pf & OD Gt",
            "Shamisen",
            "for Normal PU L1",
            "for Normal PU L2",
            "for Normal PU L3",

            "Heavy PdlBend",
            "Hard St/Syn FX",
            "StackOfSoloSynth",
            "Captain Nylon",
            "HarpNylon&String",
            "Sync Key Vox Gt",
            "Liquid Baritone",
            "String Quartet",
            "Sax over Organ",
            "FullBeardBoogie",
            "MahoganyTones",
            "EuropeanFeedback",
            "Funkenstein Bass",
            "Fuzz Bass&Syn Bs",
            "Weather Forecast",
            "FlyingJuno Brass",
            "Drop D Trance",
            "Soft Syn Lead",
            "Soft Res Lead",
            "Octa Sync Mix",
            "Filtered PolySyn",
            "Fat Power Note",
            "Anthem Approved",
            "MILD CLEAN",
            "MILD OCTAVE",
            "BRIGHT +1OCTAVE",
            "+1 OctModulation",
            "LIPSTACK DLY",
            "Heavy Gt",
            "Saturated Dreams",
          ],
        }),
        ...buildContiguousPatches({
          styleLabel: "RHYTHM",
          fromPatchNumber: [1, 1],
          toPatchNumber: [3, 2],
          bankMSB: 16,
          fromPC: 120,
          names: [
            "12st AG & Ch Org",
            "DoubleFlatHeavy",
            "SoftBrightPad+L4",
            "RICH STRINGS",
            "POLY SITAR",
            "HeavyBrassRock",
            "Syn Str.Pdl Reso",
            "TB-303 Bass",
          ],
        }),
        ...buildContiguousPatches({
          styleLabel: "RHYTHM",
          fromPatchNumber: [3, 3],
          toPatchNumber: [40, 3],
          bankMSB: 17,
          fromPC: 0,
          names: [
            "AG+Bell Pad",
            "Double Low Piano",
            "E.Piano",
            "Xylophone Plus",
            "30 String Guitar",
            "ST + TWEED",
            "LP + STACK",
            "AcGt12st+STRINGS",
            "Jazz Guitar",
            "TL&Rotary Organ",
            "Ballade Wurly",
            "RnB Section",
            "NYLON Gt+STRINGS",
            "Symphonic Rock",
            "GR Brass+Strings",
            "RockInCathedral",
            "DADGAD PHASER",
            "Asian DADGAD",
            "TL+StFlanger Pad",
            "Heavy Gt W/Sweep",
            "Fat Drive Mix",
            "Bright Gtr + Pad",
            "Electric 12str",
            "AC->12stAC(CTL",
            "Nylon String Gtr",
            "Pedal Wah",
            "Stolling Rones",
            "Flat Tuned Drive",
            "BlueGrass 12-St",
            "Bell Clean",
            "AG & Epf",
            "HnkyTonk Piano",
            "Phaser E.Pf",
            "Piano + Anlg Pad",
            "Dyno Epf w/Pad",
            "ST+FM Epf+Voice",
            "Drive Wurly",
            "80s Piano",
            "Analog Clav S&H",
            "E.PIANO/AcPIANO",
            "Pipe Organ",
            "Cheap Organ",
            "3xOrganPower",
            "Simple Clavi",
            "R12st+Clavi+Xylo",
            "Harpsichord CTL",
            "Celesta",
            "Accordion",
            "Bell&Mallet+(Bs)",
            "TE+FM Bell Pad",
            "Marimba",
            "SteelDrums/Ethno",
            "Voice Pad SL",
            "AG+Voice",
            "Rotary G & Pad",
            "Gt & Vo Unison",
            "Vox+Pf+Crystal",
            "Crunch & Voice",
            "80s Stack Piano",
            "Like 60s",
            "Reed Organ(+LP",
            "Full Section",
            "Real & Syn Brass",
            "Edge Brass",
            "ORCHESTRA",
            "PIZZICATO Gt",
            "FLANGE STRINGS",
            "PHASE STRINGS",
            "SynthBrass",
            "BLADE RUNNING",
            "Seychelles Tour",
            "EmotionalBallad",
            "Analog Voice Pad",
            "-2 Tubular & LP",
            "Bridge of Sy's",
            "Faded Cherry",
            "Acid Bass",
            "Acoustic Bass",
            "Heavy P-Funk BS",
            "for Normal PU R1",
            "for Normal PU R2",
            "for Normal PU R3",

            "DreaminResonator",
            "NashvilleRoads",
            "MoodyBaritoneGTR",
            "Rotary Poly Key",
            "Syn Brs&Ana Bell",
            "ClnCho EXP>Bell",
            "OpenE Repeater",
            "ES335 BRIGHT",
            "Dynamic TL",
            "Reggae Ricky",
            "Heavy EXPsw Up 5",
            "TIGHT TELE STACK",
            "Tele Tastic",
            "BRIGHT ST R+C",
            "POWER Ac.GUITAR",
            "MILD NYLON Gt",
            "SITAR",
            "Mandlin&AG+Acord",
            "Kalimba Pad",
            "AsianOpenG-Slide",
            "HarpsiOrch+12stG",
            "Open G Dulcimers",
            "Rotary Wurly Pls",
            "80s Analog Mix",
            "Crunch LP&St Pad",
            "DADGAD Crunch @",
            "Gt->ROCK BASS",
            "Asian Edge",
            "MostBeautifulGTR",
            "Stack Of Blues",
          ],
        }),
        ...buildContiguousPatches({
          styleLabel: "OTHER",
          fromPatchNumber: [1, 1],
          toPatchNumber: [6, 1],
          bankMSB: 17,
          fromPC: 112,
          names: [
            "Ultimate Pulse",
            "Heavy Hit&Groove",
            "Jazz Trio",
            "Seq*Tempo Dly+EG",
            "DarkSideOfTheSun",
            "KOTO DREAMS",
            "Voice Hit",
            "Heavens Bells",
            "Sine Air Bend",
            "Question+Answer",
            "Metamorphosis",
            "HighlanderGTR",
            "Sitar Fantasy",
            "GR-300 Triplet",
            "Noize Mix Drive",
            "Scat & Guitar",
          ],
        }),
        ...buildContiguousPatches({
          styleLabel: "OTHER",
          fromPatchNumber: [6, 2],
          toPatchNumber: [40, 3],
          bankMSB: 18,
          fromPC: 0,
          names: [
            "SE Pad & LP+MS",
            "DancingAcoustic",
            "Heavy Pulse",
            "NEW WAVES",
            "FourthOfFifth",
            "E Sitar& Dly Toy",
            "Trio Concerto",
            "PARADISE LOST",
            "Trademark Riff",
            "Touchy 5th",
            "Scuba-Diving",
            "Big Syn Drum",
            "Sequence Clean",
            "Acoustic Heaven",
            "SparkleBellGTR",
            "Metal Timpani",
            "Cheezy Movie",
            "Stalker Violin",
            "OverblownClnGTR",
            "MotionBuilder",
            "Pulsing Bell+EG",
            "Flying Tremolo",
            "Trance Organ",
            "Sequence Trio",
            "Extreme FX",
            "Rhythmic Pulse",
            "Scared Score",
            "EasternFluteGT",
            "Odd Guitar",
            "DissonantBeauty",
            "PluckdBaritoned",
            "GroovePusher",
            "JazzEP/BassSplit",
            "Metal Scat",
            "Quantum Physics",
            "Enigmatic Rick",
            "Euro Beat Slicer",
            "Fuzz Heaven",
            "Arabian Nights",
            "Morpheus",
            "Unison+5thPower",
            "BassFluteSaxTrio",
            "Exorbitanz",
            "Armageddon",
            "Grinder",
            "EmoCarillion",
            "Unbelievable",
            "FAB 4 Together",
            "Esoteric Vibe",
            "Deja Vu Bass",
            "GK Paradise",
            "Is Dis Fat",
            "Gladiator",
            "SlowGearSynth",
            "Oxygen Lead",
            "SteelPan + Agogo",
            "GHOSTLY",
            "SNEAKING UP",
            "Big Ben",
            "AggroClav",
            "Cinematic Art",
            "Strictly E",
            "Beat Provider",
            "Shanai+Rhythm",
            "BackToDaCrib",
            "Hyper TE Beat",
            "HOUSE FIRE",
            "Trance Groove",
            "RAINSTORM",
            "Scary Scream",
            "COMEDIAN",
            "for Normal PU O1",
            "for Normal PU O2",
            "for Normal PU O3",

            "Fantasy E.Guitar",
            "Space Altar",
            "ElectroG&Passing",
            "Sweep & Mod",
            "Tremolo Morphin",
            "Fairy Jazz GT",
            "Fine Wine(DropD)",
            "DeepWater(OpenE)",
            "Bubble in Heaven",
            "Lo B Rush Hour",
            "Trance Mission",
            "Ultraslow Groove",
            "80`s Kraftgroove",
            "Trancy CTL=BPM",
            "Trancy Riff BPM",
            "Slicer Change",
            "Drop-D Slices",
            "Bell&SynBrass Gt",
            "GR-Wonderland",
            "FallDown(ExpPdl)",
            "GtrBell (+ExpSw)",
            "ReverseGt+St Pad",
            "SingleNoteOrch",
            "Shadow Crunch Gt",
            "Dbl Crystal Bell",
            "Analog Seq & Dly",
            "Hold Bass>Wah LD",
            "Tap Dance Guitar",
            "CompuRhythm",
            "BritishRaceTrack",
          ],
        })
      );
      break;
    case "BASS":
      patchList.push(
        ...buildContiguousPatches({
          styleLabel: "LEAD",
          fromPatchNumber: [1, 1],
          toPatchNumber: [12, 3],
          bankMSB: 16,
          fromPC: 0,
          names: [
            "Double String Bs",
            "Oct Unison Lead",
            "Cotton Harp",
            "Jazz Trio",
            "Mond MG Lead",
            "Pipe & Organ",
            "Indian Fretless",
            "EP Unison",
            "Mellow Fretless",
            "AnalogBass+Pedal",
            "OrgBass+PedalSyn",
            "ModBass+PedalSyn",
            "Deep Ensemble",
            "Rock Organic",
            "Pedal Synth Bend",
            "Soft Lead",
            "70s Mond Org",
            "Flange GR-500",
            "Solo Cello",
            "Trumpet&Strings",
            "OctaPiano",
            "Strings&FL Sound",
            "Ska Melody",
            "Spacy Jazz Bass",
            "Delayed Nylon",
            "Experience",
            "Extreme Dist",
            "for Normal PU L1",
            "for Normal PU L2",
            "for Normal PU L3",

            "Saxy Bass",
            "Fat SynthBass 8+",
            "SINE UNISON BASS",
            "COOL JUMP BASS",
            "LOW OCT SAW",
            "Heavy Dst Organ",
          ],
        }),
        ...buildContiguousPatches({
          styleLabel: "RHYTHM",
          fromPatchNumber: [1, 1],
          toPatchNumber: [12, 3],
          bankMSB: 16,
          fromPC: 36,
          names: [
            "Super Saw Bass",
            "M-Man Brass",
            "Fat Upright",
            "Organ ViolinBass",
            "Bell Sweep Bass",
            "Heavy E.Piano",
            "Shaker Synth",
            "FilterBassSynth",
            "MM & Fat Poly",
            "FastTrackin'Bass",
            "Soft Bass",
            "BrightJB+SynBass",
            "Fat Synth Bass",
            "Big Synth",
            "DecayFilterBass",
            "Bass Synth",
            "Reso Fuzz Bass",
            "ACID CLAV",
            "Space Funk",
            "Trem E.Piano",
            "Bass + Clav",
            "OctaClavz",
            "High Strings",
            "Brass Mix",
            "Organ Bass",
            "Octave M-Man",
            "P-Bass Crunch",
            "for Normal PU R1",
            "for Normal PU R2",
            "for Normal PU R3",

            "Rhds Piano Bass",
            "Analog-y",
            "Fat Alpha Bass",
            "Synth Reso Bass",
            "MONSTER BASS SAW",
            "SlapSynthCTL+EXP",
          ],
        }),
        ...buildContiguousPatches({
          styleLabel: "OTHER",
          fromPatchNumber: [1, 1],
          toPatchNumber: [12, 3],
          bankMSB: 16,
          fromPC: 72,

          names: [
            "Ultimate Pulse",
            "Ambient Sparkle",
            "Auto Groove",
            "Avalon",
            "Bollywood Stack",
            "Gel Sequence",
            "Seq.Str.Hit",
            "Vint Seq.Bass",
            "Techno Sequence",
            "Tubular Strings",
            "TIME>TRAVELER",
            "STRINGTHEORY",
            "Ambient Organ",
            "RingLoop&E.Piano",
            "Unknown Kingdom",
            "Arrival Of King",
            "Ringing Bell",
            "TOKYO LIGHTS",
            "Sad Memory",
            "Wandering Pipe",
            "LUNAR LANDING",
            "Techno Opening",
            "Inner Journey",
            "HOUSE PARTY",
            "Compu-Strings",
            "5th & Groovin",
            "Shamisen Beat",
            "for Normal PU O1",
            "for Normal PU O2",
            "for Normal PU O3",

            "WINE-N-BASSDELAY",
            "AEROPLANESUSTAIN",
            "Space SAW",
            "Gtr Hi/Bass Lo",
            "CompuRhythm",
            "S&H Groove/CTL",
          ],
        })
      );
  }
  patchList.push(
    ...buildContiguousPatches({
      styleLabel: "USER",
      fromPatchNumber: [1, 1],
      toPatchNumber: [43, 2],
      bankMSB: 0,
      fromPC: 0,
      fromUserPatch: 0,
    }),
    ...buildContiguousPatches({
      styleLabel: "USER",
      fromPatchNumber: [43, 3],
      toPatchNumber: [86, 1],
      bankMSB: 1,
      fromPC: 0,
      fromUserPatch: 128,
    }),
    ...buildContiguousPatches({
      styleLabel: "USER",
      fromPatchNumber: [86, 2],
      toPatchNumber: [99, 3],
      bankMSB: 2,
      fromPC: 0,
      fromUserPatch: 256,
    })
  );
  return {
    patchList,
  };
}

export type RolandGR55PatchMap = Readonly<{
  patchList: readonly Readonly<{
    styleLabel: string;
    patchNumberLabel: string;
    bankMSB: number;
    pc: number;
    userPatch:
      | Readonly<{
          patchNumber: number;
          baseAddress: number;
        }>
      | undefined;
    builtInName: string | undefined;
  }>[];
}>;

export const RolandGR55PatchMapGuitarMode: RolandGR55PatchMap =
  buildPatchMap("GUITAR");
export const RolandGR55PatchMapBassMode: RolandGR55PatchMap =
  buildPatchMap("BASS");
